"""empty message

Revision ID: 6a052042f118
Revises: 
Create Date: 2021-12-12 14:18:42.523712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a052042f118'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_country'), 'city', ['country'], unique=False)
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=True)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coffee', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_coffee'), 'tag', ['coffee'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_icon'), 'user', ['icon'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('shop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shopName', sa.String(length=64), nullable=True),
    sa.Column('ownerName', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=127), nullable=True),
    sa.Column('website', sa.String(length=127), nullable=True),
    sa.Column('about_shop', sa.String(length=500), nullable=True),
    sa.Column('speciality', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('menu', sa.String(length=500), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_address'), 'shop', ['address'], unique=False)
    op.create_index(op.f('ix_shop_icon'), 'shop', ['icon'], unique=False)
    op.create_index(op.f('ix_shop_menu'), 'shop', ['menu'], unique=False)
    op.create_index(op.f('ix_shop_ownerName'), 'shop', ['ownerName'], unique=False)
    op.create_index(op.f('ix_shop_shopName'), 'shop', ['shopName'], unique=False)
    op.create_index(op.f('ix_shop_website'), 'shop', ['website'], unique=False)
    op.create_table('user2_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('noiseLevel', sa.Integer(), nullable=True),
    sa.Column('customerService', sa.Integer(), nullable=True),
    sa.Column('liveMusic', sa.Boolean(), nullable=True),
    sa.Column('atmosphere', sa.String(length=64), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_details_atmosphere'), 'review_details', ['atmosphere'], unique=False)
    op.create_index(op.f('ix_review_details_customerService'), 'review_details', ['customerService'], unique=False)
    op.create_index(op.f('ix_review_details_liveMusic'), 'review_details', ['liveMusic'], unique=False)
    op.create_index(op.f('ix_review_details_noiseLevel'), 'review_details', ['noiseLevel'], unique=False)
    op.create_table('user2_shop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user2_shop')
    op.drop_index(op.f('ix_review_details_noiseLevel'), table_name='review_details')
    op.drop_index(op.f('ix_review_details_liveMusic'), table_name='review_details')
    op.drop_index(op.f('ix_review_details_customerService'), table_name='review_details')
    op.drop_index(op.f('ix_review_details_atmosphere'), table_name='review_details')
    op.drop_table('review_details')
    op.drop_table('user2_tag')
    op.drop_index(op.f('ix_shop_website'), table_name='shop')
    op.drop_index(op.f('ix_shop_shopName'), table_name='shop')
    op.drop_index(op.f('ix_shop_ownerName'), table_name='shop')
    op.drop_index(op.f('ix_shop_menu'), table_name='shop')
    op.drop_index(op.f('ix_shop_icon'), table_name='shop')
    op.drop_index(op.f('ix_shop_address'), table_name='shop')
    op.drop_table('shop')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_icon'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tag_coffee'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.drop_index(op.f('ix_city_country'), table_name='city')
    op.drop_table('city')
    # ### end Alembic commands ###
